import { Audio } from "expo-av";

// Module-level store - avoids passing soundEnabled through closures
let _soundEnabled = true;

export function setSoundEnabled(enabled: boolean) {
  _soundEnabled = enabled;
}

function isSoundEnabled(): boolean {
  return _soundEnabled;
}

// Bundled sound assets (generated by scripts/generate-sounds.js)
const SOUNDS = {
  cardFlip: require("../assets/sounds/card-flip.wav"),
  cardDeal: require("../assets/sounds/card-deal.wav"),
  success: require("../assets/sounds/success.wav"),
} as const;

let isAudioConfigured = false;

async function ensureAudioConfigured() {
  if (isAudioConfigured) return;
  try {
    await Audio.setAudioModeAsync({
      playsInSilentModeIOS: true,
      staysActiveInBackground: false,
      shouldDuckAndroid: true,
      playThroughEarpieceAndroid: false,
      interruptionModeAndroid: 1,
      interruptionModeIOS: 1,
    });
    isAudioConfigured = true;
  } catch {
    // ignore
  }
}

async function playSound(enabled: boolean, source: number) {
  if (!enabled) return;
  try {
    await ensureAudioConfigured();
    const { sound } = await Audio.Sound.createAsync(
      source,
      { shouldPlay: true }
    );
    sound.setOnPlaybackStatusUpdate((status) => {
      if (status.isLoaded && status.didJustFinish) {
        sound.unloadAsync().catch(() => {});
      }
    });
  } catch {
    // Silently ignore - sound may not be supported on this platform
  }
}

export function playCardFlip() {
  playSound(isSoundEnabled(), SOUNDS.cardFlip as number);
}

export function playCardDeal() {
  playSound(isSoundEnabled(), SOUNDS.cardDeal as number);
}

export function playSuccess() {
  playSound(isSoundEnabled(), SOUNDS.success as number);
}

export function playTap() {
  playSound(isSoundEnabled(), SOUNDS.cardFlip as number);
}

export function playShow() {
  playSound(isSoundEnabled(), SOUNDS.success as number);
}
